version: "3.9"
services:
  api:
    build: .
    ports:
      - "4444:4444"
    volumes:
      - .:/usr/src/app # bind mount
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: distributask
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: distributask
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5-alpine

volumes:
  postgres:
